#!/bin/bash

# Configure the iMac side of Phase 6: restricted verified capture receiver.

set -euo pipefail

export LC_ALL=C
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

ORIGINAL_ARGS=("$@")
DRY_RUN=0
CLIENT_KEY_FILE=""
# Identity check only — not a bind address. The receiver itself listens on
# all interfaces (see sshd_content below); this just confirms the script
# is being run on the intended Mac before making system changes, using a
# stable identity (mDNS hostname) rather than a DHCP-assigned IP that can
# and did change.
EXPECTED_HOSTNAME="imac"
RECEIVER_PORT="2222"
RECEIVER_USER="admin"
RECEIVER_GROUP="staff"
DESTINATION="/Users/admin/Pictures/Optic"
STATE_DIR="/Library/Application Support/Project Optic/capture-receiver"
BACKUP_DIR="$STATE_DIR/backups"
HOST_KEY="$STATE_DIR/ssh_host_ed25519_key"
AUTHORIZED_KEYS="/Users/admin/.config/optic/capture_receiver_authorized_keys"
SSHD_CONFIG="$STATE_DIR/sshd_config"
RECEIVER_SOURCE="$(cd "$(dirname "$0")" && pwd)/optic-capture-receiver.sh"
RECEIVER_TARGET="/usr/local/libexec/optic-capture-receiver"
PLIST="/Library/LaunchDaemons/dev.optic.capture-receiver.plist"
LOG_DIR="/Library/Logs/Project Optic"
EXPORTED_HOST_KEY="/Users/admin/.config/optic/capture_receiver_host_ed25519.pub"
TEMPORARY=""

usage() {
    cat <<'EOF'
Usage: setup-phase-06-imac-receiver.sh [--dry-run] --client-key FILE [--help]

Configures a dedicated capture-only SSH receiver on port 2222 (all
interfaces) and stores verified files in /Users/admin/Pictures/Optic.

  --dry-run          Report required changes without modifying the iMac.
  --client-key FILE  Pi capture-transfer public key generated by Pi setup.
  --help             Display this help.
EOF
}

while (($#)); do
    case "$1" in
        --dry-run) DRY_RUN=1 ;;
        --client-key)
            [[ $# -ge 2 ]] || { printf '%s\n' 'Missing value for --client-key' >&2; exit 64; }
            CLIENT_KEY_FILE=$2
            shift
            ;;
        --help|-h) usage; exit 0 ;;
        *) printf 'Unknown argument: %s\n' "$1" >&2; usage >&2; exit 64 ;;
    esac
    shift
done

[[ -n "$CLIENT_KEY_FILE" ]] || { printf '%s\n' '--client-key is required.' >&2; exit 64; }
[[ -r "$CLIENT_KEY_FILE" ]] || { printf 'Client key is unreadable: %s\n' "$CLIENT_KEY_FILE" >&2; exit 69; }
read -r client_key_type client_key_data client_key_comment < "$CLIENT_KEY_FILE"
[[ "$client_key_type" == "ssh-ed25519" && -n "$client_key_data" ]] || {
    printf '%s\n' 'Client key must be an ssh-ed25519 public key.' >&2
    exit 69
}
ssh-keygen -l -f "$CLIENT_KEY_FILE" >/dev/null 2>&1 || {
    printf '%s\n' 'Client key failed ssh-keygen validation.' >&2
    exit 69
}
client_key_content="restrict,command=\"$RECEIVER_TARGET\" $client_key_type $client_key_data Project-Optic-capture-transfer"

cleanup() {
    [[ -z "$TEMPORARY" ]] || rm -f -- "$TEMPORARY"
}
trap cleanup EXIT

current_hostname=$(scutil --get LocalHostName 2>/dev/null || true)

sshd_content=$(cat <<EOF
# Managed by Project Optic setup-phase-06-imac-receiver.sh
Port $RECEIVER_PORT
HostKey "$HOST_KEY"
PidFile /var/run/optic-capture-sshd.pid
AuthorizedKeysFile "$AUTHORIZED_KEYS"
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey
PermitEmptyPasswords no
PermitRootLogin no
AllowUsers $RECEIVER_USER
AllowAgentForwarding no
AllowTcpForwarding no
AllowStreamLocalForwarding no
GatewayPorts no
PermitTunnel no
X11Forwarding no
PermitTTY no
PermitUserRC no
UsePAM no
StrictModes yes
MaxAuthTries 2
MaxSessions 1
LoginGraceTime 20
ClientAliveInterval 30
ClientAliveCountMax 2
LogLevel VERBOSE
ForceCommand $RECEIVER_TARGET
EOF
)

plist_content=$(cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>dev.optic.capture-receiver</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/sbin/sshd</string>
        <string>-D</string>
        <string>-e</string>
        <string>-f</string>
        <string>$SSHD_CONFIG</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>5</integer>
    <key>StandardOutPath</key>
    <string>$LOG_DIR/capture-receiver.log</string>
    <key>StandardErrorPath</key>
    <string>$LOG_DIR/capture-receiver.log</string>
</dict>
</plist>
EOF
)

file_matches() {
    local path=$1 content=$2
    [[ -r "$path" ]] && cmp -s "$path" <(printf '%s\n' "$content")
}

if ((DRY_RUN)); then
    printf '%s\n' 'Project Optic Phase 6 iMac dry run'
    [[ "$current_hostname" == "$EXPECTED_HOSTNAME" ]] &&
        printf '[OK] Running on the intended host (%s).\n' "$EXPECTED_HOSTNAME" ||
        printf '[BLOCKED] Not running on the intended host (expected %s, got %s).\n' \
            "$EXPECTED_HOSTNAME" "${current_hostname:-unknown}"
    [[ -x "$RECEIVER_SOURCE" ]] && printf '%s\n' '[OK] Receiver helper is available.' ||
        printf '[BLOCKED] Receiver helper is missing: %s\n' "$RECEIVER_SOURCE"
    [[ -d "$DESTINATION" ]] && printf '[OK] Destination exists: %s\n' "$DESTINATION" ||
        printf '[CHANGE] Create destination: %s\n' "$DESTINATION"
    [[ -f "$HOST_KEY" ]] && printf '%s\n' '[OK] Dedicated receiver host key exists.' ||
        printf '%s\n' '[CHANGE] Generate a dedicated receiver host key.'
    file_matches "$AUTHORIZED_KEYS" "$client_key_content" &&
        printf '%s\n' '[OK] Pi capture key is authorized.' ||
        printf '%s\n' '[CHANGE] Authorize only the supplied Pi capture key.'
    file_matches "$SSHD_CONFIG" "$sshd_content" &&
        printf '%s\n' '[OK] Dedicated sshd configuration matches.' ||
        printf '%s\n' '[CHANGE] Install dedicated sshd configuration.'
    file_matches "$PLIST" "$plist_content" &&
        printf '%s\n' '[OK] LaunchDaemon configuration matches.' ||
        printf '%s\n' '[CHANGE] Install and start the receiver LaunchDaemon.'
    exit 0
fi

if ((EUID != 0)); then
    if command -v sudo >/dev/null 2>&1; then
        exec sudo -- "$0" "${ORIGINAL_ARGS[@]}"
    fi
    printf '%s\n' 'This setup must run as root.' >&2
    exit 77
fi

[[ "$current_hostname" == "$EXPECTED_HOSTNAME" ]] || {
    printf 'This is not the intended host (expected %s, got %s); no changes were made.\n' \
        "$EXPECTED_HOSTNAME" "${current_hostname:-unknown}" >&2
    exit 69
}
[[ -x "$RECEIVER_SOURCE" ]] || {
    printf 'Receiver helper is missing or not executable: %s\n' "$RECEIVER_SOURCE" >&2
    exit 69
}

printf '%s\n' 'Configuring Project Optic Phase 6 iMac capture receiver'

install -d -m 0755 -o "$RECEIVER_USER" -g "$RECEIVER_GROUP" "$DESTINATION"
install -d -m 0700 -o "$RECEIVER_USER" -g "$RECEIVER_GROUP" "$DESTINATION/.incoming"
install -d -m 0700 -o root -g wheel "$STATE_DIR" "$BACKUP_DIR"
install -d -m 0755 -o root -g wheel /usr/local/libexec "$LOG_DIR"
install -d -m 0755 -o "$RECEIVER_USER" -g "$RECEIVER_GROUP" /Users/admin/.config/optic

install -m 0755 -o root -g wheel "$RECEIVER_SOURCE" "$RECEIVER_TARGET"

if [[ ! -f "$HOST_KEY" ]]; then
    ssh-keygen -q -t ed25519 -N '' -C 'Project-Optic-capture-receiver' -f "$HOST_KEY"
    chown root:wheel "$HOST_KEY" "$HOST_KEY.pub"
    chmod 0600 "$HOST_KEY"
    chmod 0644 "$HOST_KEY.pub"
    printf 'Generated %s.\n' "$HOST_KEY"
fi

printf '%s\n' "$client_key_content" > "$AUTHORIZED_KEYS"
chown "$RECEIVER_USER:$RECEIVER_GROUP" "$AUTHORIZED_KEYS"
chmod 0600 "$AUTHORIZED_KEYS"

install_managed() {
    local path=$1 content=$2 mode=$3
    local backup
    if [[ -e "$path" ]] && ! file_matches "$path" "$content"; then
        backup="$BACKUP_DIR/$(basename "$path").$(date +%Y%m%dT%H%M%S).bak"
        cp -a -- "$path" "$backup"
        printf 'Backed up previous file to %s\n' "$backup"
    fi
    TEMPORARY=$(mktemp "$(dirname "$path")/.$(basename "$path").XXXXXX")
    printf '%s\n' "$content" > "$TEMPORARY"
    chmod "$mode" "$TEMPORARY"
    chown root:wheel "$TEMPORARY"
    mv -f -- "$TEMPORARY" "$path"
    TEMPORARY=""
    printf 'Installed %s\n' "$path"
}

install_managed "$SSHD_CONFIG" "$sshd_content" 0600
install_managed "$PLIST" "$plist_content" 0644
plutil -lint "$PLIST"
/usr/sbin/sshd -t -f "$SSHD_CONFIG"

launchctl bootout system/dev.optic.capture-receiver 2>/dev/null || true
launchctl bootstrap system "$PLIST"
launchctl kickstart -k system/dev.optic.capture-receiver

for attempt in {1..10}; do
    nc -z -w 1 127.0.0.1 "$RECEIVER_PORT" && break
    sleep 1
done
nc -z -w 2 127.0.0.1 "$RECEIVER_PORT"

install -m 0644 -o "$RECEIVER_USER" -g "$RECEIVER_GROUP" \
    "$HOST_KEY.pub" "$EXPORTED_HOST_KEY"

printf '%s\n' 'Phase 6 iMac receiver is listening with public-key-only forced-command access.'
printf 'Exported receiver host key: %s\n' "$EXPORTED_HOST_KEY"